default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mm_app
  pool: 5
  username: innu
  password: innU2020
  socket: /var/lib/mysql/mysql.sock
  host: mm-appli-web.cmtmnmswftyh.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: mm_app

test:
  <<: *default
  database: mm_app

production:
  <<: *default
  database: mm_app